#!/bin/sh

prog_name=$0
version="beta"
year=2025

fatal() {
	echo "fatal: $*" >&2
	exit 1
}

usage() {
	cat <<EOF
Usage: $prog_name [OPTION]...

      --help     print this help and exit.
      --version  print version information.
      --list     print avaliable modules.
      --import   import named module into current package.
      --update   update packages in your current gcklib.

EOF
}

version() {
	cat <<EOF
$prog_name $version $(git rev-list --count --all)
Copyright (C) $year GCK.
This is free software: you are free to change and redistribute it.
There is NO WARRNTY, to the extent permitted by law.
EOF
}

list() {
	ls lib | grep ".c" | cut -d. -f1
}

import() {
	local module=$1
	module=$($module | xarg)
	cp ${module}.h lib/
	cp ${nodule}.c lib/
}

[ ! -f "./gcklib-tool" ] && fatal run this in the gcklib directory.

for arg; do
case "$arg" in
--help) usage ;;
--version) version ;;
--list) list ;;
--import) import ${arg#*} ;;
--update) echo "TODO" ;;
*) printf "Unrecognized option %s\n" "$arg" ;;
esac
done
