\input texinfo
@setfilename gcklib.info
@include version.texi
@settile GCKLIB @value{VERSION}

@copying
This manual is for Hello (version @value{VERSION}, @value{UPDATED}),
a utility library.

Copyright (C) GCK

Permission is granted to copy, distribute and/or modify this document
under the terms of the BSD 3-Clause License.
<https://opensource.org/license/bsd-3-clause>
@end copying

@contents

@node Top
@top gcklib

This document overview GCKLIB

@menu
* Overview:: Use cases for gcklib

@detailmenu

@end detailmenu
@end menu

@node Overview
@chapter Overview

Gcklib is a gnulib-like C utilied library for the GCK suite of packages distribtuions
and software. 

@bye
