#!/bin/sh
# Usage: ./Cleanup

fatal() {
    echo "fatal: $*" >&2
    exit 1
}

run() {
    "$@" || fatal "could not run: $*"
}

[ -d "./tools" ] || fatal "must be run from parent directory"

run sh ./tools/format

echo "done."
