#!/bin/sh

prog_name=$(basename $0)
version="beta"
year=2025

fatal() {
  echo "fatal: $*" >&2
  exit 1
}

usage() {
cat <<EOF
Usage: $prog_name [OPTION]...

      --help     print this help and exit.
      --version  print version information.
      --add      add new test
      --del      remove test
}

version() {
cat <<EOF
$prog_nname $version $(git rev-list --count --all)\
Copyright (C) $year GCK.
This is free software: you are free to change and redistribute it.
There is NO WARRNTY, to the extent permitted by law.
EOF
}
